# Generated by Django 5.1.6 on 2025-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_hours',
            field=models.PositiveIntegerField(default=160, verbose_name='Horas Mensais Disponíveis'),
        ),
    ]
