# Generated by Django 5.1.6 on 2025-02-07 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stacks', '0002_userstack_created_by_userstack_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do projeto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('estimated_hours', models.PositiveBigIntegerField(verbose_name='Horas estimadas')),
                ('start_dat', models.DateField(verbose_name='Data de inicio')),
                ('end_date', models.DateField(verbose_name='Data prevista de termino')),
                ('status', models.CharField(choices=[('ON_HOLD', 'Em Pausa'), ('IN_PROGRESS', 'Em Andamento'), ('PLANNING', 'Em Planejamento'), ('COMPLETED', 'Concluído')], default='PLANNING', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tech_leader', models.ForeignKey(limit_choices_to={'user_type': 'TL'}, on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Tech Leader')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('hours_per_month', models.PositiveIntegerField(help_text='Horas mensais alocadas para esse desenvolvedor', verbose_name='Horas por mês')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('developer', models.ForeignKey(limit_choices_to={'user_type': 'DEV'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('stack', models.ForeignKey(help_text='Stack que o desenvolvedor utilizará neste projeto', on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(related_name='developer_projects', through='projects.ProjectDeveloper', to=settings.AUTH_USER_MODEL, verbose_name='Desenvolvedores'),
        ),
        migrations.CreateModel(
            name='ProjectStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_developers', models.PositiveIntegerField(default=1, help_text='Número de desenvolvedores necessários para esta stack')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'unique_together': {('project', 'stack')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='stacks',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectStack', to='stacks.stack', verbose_name='Stacks do projeto'),
        ),
    ]
