# Generated by Django 5.1.6 on 2025-02-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Em Planejamento'), ('COMPLETED', 'Concluído'), ('ON_HOLD', 'Em Pausa'), ('IN_PROGRESS', 'Em Andamento')], default='PLANNING', max_length=20),
        ),
    ]
