# Generated by Django 5.1.6 on 2025-02-07 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_dat',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='Data de Término Previsto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Concluído'), ('PLANNING', 'Em Planejamento'), ('ON_HOLD', 'Em Pausa'), ('IN_PROGRESS', 'Em Andamento')], default='PLANNING', max_length=20),
        ),
    ]
