# Generated by Django 5.1.6 on 2025-02-10 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_start_dat_project_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('ON_HOLD', 'Em Pausa'), ('PLANNING', 'Em Planejamento'), ('COMPLETED', 'Concluído')], default='PLANNING', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Tipo de ação realizada (ex: 'updated', 'created', etc)", max_length=50)),
                ('description', models.TextField(help_text='Descrição detalhada da mudança')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Quando a mudança foi realizada')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='projects.project')),
                ('user', models.ForeignKey(help_text='Usuário que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
