# Generated by Django 5.1.6 on 2025-02-10 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status_projectchangelog'),
        ('stacks', '0002_userstack_created_by_userstack_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdeveloper',
            name='stack',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Descrição detalhada do projeto, seus objetivos e escopo', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(help_text='Desenvolvedores alocados no projeto com suas respectivas stacks e horas', related_name='developer_projects', through='projects.ProjectDeveloper', to=settings.AUTH_USER_MODEL, verbose_name='Desenvolvedores'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(help_text='Data prevista para conclusão do projeto', verbose_name='Data de Término Previsto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_hours',
            field=models.PositiveBigIntegerField(help_text='Total de horas estimadas para a conclusão do projeto', verbose_name='Horas estimadas'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Nome único que identifica o projeto', max_length=255, verbose_name='Nome do projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stacks',
            field=models.ManyToManyField(help_text='Stacks tecnológicas necessárias para o projeto', related_name='projects', through='projects.ProjectStack', to='stacks.stack', verbose_name='Stacks do projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text='Data planejada para início do projeto', verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Em Planejamento'), ('IN_PROGRESS', 'Em Andamento'), ('ON_HOLD', 'Em Pausa'), ('COMPLETED', 'Concluído')], default='PLANNING', help_text='Status atual do projeto (Planejamento, Em Andamento, Concluído ou Em Pausa)', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_leader',
            field=models.ForeignKey(help_text='Tech Leader responsável pelo projeto. Deve ter as stacks necessárias', limit_choices_to={'user_type': 'TL'}, on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Tech Leader'),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='developer',
            field=models.ForeignKey(help_text="Desenvolvedor alocado no projeto (deve ter o tipo 'DEV')", limit_choices_to={'user_type': 'DEV'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='end_date',
            field=models.DateField(help_text='Data de término prevista para a alocação do desenvolvedor'),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='hours_per_month',
            field=models.PositiveIntegerField(help_text='Quantidade de horas mensais que o desenvolvedor dedicará ao projeto', verbose_name='Horas por mês'),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='project',
            field=models.ForeignKey(help_text='Projeto ao qual o desenvolvedor está alocado', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='start_date',
            field=models.DateField(help_text='Data de início da alocação do desenvolvedor no projeto'),
        ),
        migrations.AlterField(
            model_name='projectstack',
            name='project',
            field=models.ForeignKey(help_text='Projeto ao qual esta stack está associada', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectstack',
            name='stack',
            field=models.ForeignKey(help_text='Stack tecnológica necessária para o projeto', on_delete=django.db.models.deletion.CASCADE, to='stacks.stack'),
        ),
    ]
