# Generated by Django 5.1.6 on 2025-02-10 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projectdeveloper_stack_and_more'),
        ('stacks', '0002_userstack_created_by_userstack_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeveloper',
            name='stack',
            field=models.ForeignKey(help_text='Stack que o desenvolvedor utilizará neste projeto', null=True, on_delete=django.db.models.deletion.CASCADE, to='stacks.stack'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ON_HOLD', 'Em Pausa'), ('COMPLETED', 'Concluído'), ('PLANNING', 'Em Planejamento'), ('IN_PROGRESS', 'Em Andamento')], default='PLANNING', help_text='Status atual do projeto (Planejamento, Em Andamento, Concluído ou Em Pausa)', max_length=20),
        ),
    ]
