# Generated by Django 5.1.6 on 2025-02-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectdeveloper_stack_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('PLANNING', 'Em Planejamento'), ('COMPLETED', 'Concluído'), ('ON_HOLD', 'Em Pausa')], default='PLANNING', help_text='Status atual do projeto (Planejamento, Em Andamento, Concluído ou Em Pausa)', max_length=20),
        ),
    ]
