# Generated by Django 5.1.6 on 2025-02-10 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ON_HOLD', 'Em Pausa'), ('COMPLETED', 'Concluído'), ('PLANNING', 'Em Planejamento'), ('IN_PROGRESS', 'Em Andamento')], default='PLANNING', help_text='Status atual do projeto (Planejamento, Em Andamento, Concluído ou Em Pausa)', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 3, 12), help_text='Data de término prevista para a alocação do desenvolvedor'),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 2, 10), help_text='Data de início da alocação do desenvolvedor no projeto'),
        ),
    ]
