# Generated by Django 5.1.6 on 2025-02-12 12:19

import django.utils.timezone
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_status_alter_projectdeveloper_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Em Planejamento'), ('COMPLETED', 'Concluído'), ('IN_PROGRESS', 'Em Andamento'), ('ON_HOLD', 'Em Pausa')], default='PLANNING', help_text='Status atual do projeto (Planejamento, Em Andamento, Concluído ou Em Pausa)', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='end_date',
            field=models.DateField(default=projects.models.default_end_date, help_text='Data de término prevista para a alocação do desenvolvedor'),
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Data de início da alocação do desenvolvedor no projeto'),
        ),
    ]
