# Generated by Django 5.1.6 on 2025-02-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='projectdeveloper',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='projectstack',
            options={'ordering': ['stack__name']},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ON_HOLD', 'Em Pausa'), ('COMPLETED', 'Concluído'), ('PLANNING', 'Em Planejamento'), ('IN_PROGRESS', 'Em Andamento')], default='PLANNING', help_text='Status atual do projeto (Planejamento, Em Andamento, Concluído ou Em Pausa)', max_length=20),
        ),
    ]
